version: '3.8'

services:
#  client:
#    container_name: "myFinance-client"
#    restart: always
#    env_file: ".env"
#    build:
#      context: ./client
#      target: dev
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./client/src:/app/client/src
#    ports:
#      - 80:${VITE_CLIENT_PORT}
#    command: yarn run dev
#    networks:
#      dev_net:

  server:
    container_name: "myFinance-server"
    restart: always
    depends_on:
      - redis
    env_file: ".env"
    build:
      context: ./server
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - ./server/src:/app/server/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      dev_net:
    command: yarn run dev

  redis:
    image: redis
    container_name: "redis"
    env_file: ".env"
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_cache:/data
    networks:
      dev_net:

volumes:
  redis_cache:
    driver: local

networks:
  dev_net: