version: '3.8'

services:
#  client:
#    container_name: "myFinance-client"
#    restart: always
#    env_file: ".env"
#    build:
#      context: ./client
#      target: dev
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./client/src:/app/client/src
#    ports:
#      - 80:${VITE_CLIENT_PORT}
#    command: yarn run dev
#    networks:
#      dev_net:

  server:
    container_name: "myFinance-server"
    restart: always
    env_file: ".env"
    build:
      context: ./server
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - ./server/src:/app/server/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      dev_net:
    command: yarn run start:dev

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-db-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
      PGADMIN_DEFAULT_PASSWORD: 'teste'
    ports:
      - "16543:80"
    networks:
      - postgres-db-network

#  redis:
#    image: redis
#    container_name: "redis"
#    env_file: ".env"
#    restart: always
#    ports:
#      - ${REDIS_PORT}:${REDIS_PORT}
#    command: redis-server --requirepass ${REDIS_PASSWORD}
#    volumes:
#      - redis_cache:/data
#    networks:
#      dev_net:

volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
#  redis_cache:
#    driver: local

networks:
  dev_net:
  postgres-db-network:
    driver: bridge
